#!/bin/bash

CONFIG_DIR="$HOME/.config"

HYPR_CONFIG_DIR="$CONFIG_DIR/hypr"
HYPR_CONFIG="$HYPR_CONFIG_DIR/hyprland.conf"
HYPR_PAPER_CONFIG="$HYPR_CONFIG_DIR/hyprpaper.conf"
HYPR_WALLPAPERS_DIR="/opt/wall"
HYPR_DEFUALT_WALLPAPER="$HYPR_WALLPAPERS_DIR/default.jpg"

FOOT_CONFIG_DIR="$CONFIG_DIR/foot"
FOOT_CONFIG="$FOOT_CONFIG_DIR/foot.ini"

ROFI_CONFIG_DIR="$HOME/.config/rofi"
ROFI_CONFIG="$ROFI_CONFIG_DIR/config.rasi"

ROFIMOJI_CONFIG="$HOME/.config/rofimoji.rc"

##

if [[ $1 = "r" ]]; then
    exit 0
fi

##

mkdir -p $CONFIG_DIR

##

mkdir -p $HYPR_CONFIG_DIR
echo "[gem] [config] [hyprland] Targeting $HYPR_CONFIG"
cp /opt/gem/ext/hyprland.config.default $HYPR_CONFIG

echo "[gem] [config] [hyprpaper]"
cp /opt/gem/ext/hyprpaper.config.default $HYPR_PAPER_CONFIG
sudo mkdir -p $HYPR_WALLPAPERS_DIR
#if [[ ! -f "$HYPR_DEFUALT_WALLPAPER" ]]; then
#    sudo wget -O $HYPR_DEFUALT_WALLPAPER https://4kwallpapers.com/images/wallpapers/valley-of-fire-state-park-road-tarmac-highway-nevada-3648x5472-1096.jpg
#fi
if [[ ! -d $HYPR_WALLPAPERS_DIR ]]; then
    sudo git clone https://github.com/Eshnek/wall.git $HYPR_WALLPAPERS_DIR
fi

echo "[gem] [config] [foot]"
mkdir -p $FOOT_CONFIG_DIR
cp -f /opt/gem/ext/foot.ini $FOOT_CONFIG

echo "[gem] [config] [rofi]"
mkdir -p $ROFI_CONFIG_DIR
printf '@theme "gruvbox-dark-hard"\n' > $ROFI_CONFIG

echo "[gem] [config] [electron-flags]"
echo '--ozone-platform-hint=auto' | tee $HOME/.config/electron-flags.conf
echo '--ozone-platform=wayland' | tee $HOME/.config/electron17-flags.conf

echo "[gem] [config] [rofimoji]"
printf 'action = copy\nclipboarder = wl-copy\n' > $ROFIMOJI_CONFIG