#!/bin/bash

CONFIG_DIR="$HOME/.config"

HYPR_CONFIG_DIR="$CONFIG_DIR/hypr"
HYPR_CONFIG="$HYPR_CONFIG_DIR/hyprland.conf"
HYPR_PAPER_CONFIG="$HYPR_CONFIG_DIR/hyprpaper.conf"
HYPR_WALLPAPERS_DIR="/opt/wall"

FONTS_DIR="$HOME/fonts"
IOSEVKA_ZIP_NAME="iosevka.zip"
IOSEVKA_ZIP="$FONTS_DIR/$IOSEVKA_ZIP_NAME"

FOOT_CONFIG_DIR="$CONFIG_DIR/foot"
FOOT_CONFIG="$FOOT_CONFIG_DIR/foot.ini"

ROFI_CONFIG_DIR="$HOME/.config/rofi"
ROFI_CONFIG="$ROFI_CONFIG_DIR/config.rasi"

##

if [[ $1 = "r" ]]; then
    exit 0
fi

##

mkdir -p $HYPR_CONFIG_DIR
echo "[gem] [config] [hyprland] Targeting $HYPR_CONFIG"
cp /opt/gem/ext/hyprland.config.default $HYPR_CONFIG

echo "[gem] [config] [hyprpaper]"
cp /opt/gem/ext/hyprpaper.config.default $HYPR_PAPER_CONFIG
sudo mkdir -p $HYPR_WALLPAPERS_DIR
sudo wget -O $HYPR_WALLPAPERS_DIR/default.jpg https://4kwallpapers.com/images/wallpapers/valley-of-fire-state-park-road-tarmac-highway-nevada-3648x5472-1096.jpg

echo "[gem] [hyprland] [fonts] [iosevka]"
mkdir -p $FONTS_DIR
if [[ ! -f "$FONTS_DIR/" ]]; then
    wget -O $IOSEVKA_ZIP https://github.com/be5invis/Iosevka/releases/download/v17.1.0/super-ttc-iosevka-17.1.0.zip
fi
cd $FONTS_DIR
unzip -o $IOSEVKA_ZIP_NAME
sudo cp -f $FONTS_DIR/iosevka.ttc /usr/share/fonts
fc-cache --force

echo "[gem] [config] [foot]"
mkdir -p $FOOT_CONFIG_DIR
cp -f /opt/gem/ext/foot.ini $FOOT_CONFIG

echo "[gem] [config] [rofi]"
mkdir -p $ROFI_CONFIG_DIR
printf '@theme "gruvbox-dark-hard"\n' > $ROFI_CONFIG