#!/bin/bash

DEPS="base-devel gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms \
libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols \
cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland libinput"

HYPR_DIR="~/hypr"
HYPR_CONFIG_DIR="~/.config/hypr"
HYPR_CONFIG="$HYPR_CONFIG_DIR/hyprland.conf"

SESSIONS_DIR="/usr/share/wayland-sessions"

remove_hypr_dir() {
    rm -rf $HYPR_DIR
    rm -rf $HYPR_CONFIG_DIR
}

if [[ $1 = "r" ]]; then
    gem pac R $DEPS
    remove_hypr_dir
    
    exit 0
fi

gem pac S $DEPS

remove_hypr_dir
git clone --recursive https://github.com/hyprwm/Hyprland $HYPR_DIR || exit 1
cd $HYPR_DIR

sudo make install

mkdir -p $SESSIONS_DIR
cp /opt/gem/ext/hyprland.desktop $SESSIONS_DIR

mkdir -p $HYPR_CONFIG_DIR
cp /opt/gem/ext/hyprland.config.default $HYPR_CONFIG