#!/bin/bash

if [[ $1 = "r" ]]; then
    systemctl disable gdm
    gem pac R gdm
    echo "[gem] [disable] [service] gdm"
    
    exit 0
fi

gem pac S gdm
systemctl enable gdm
echo "[gem] [enable] [service] gdm"