#!/bin/bash

gem pac S gdm
systemctl enable gdm
echo "[gem] [enable] [service] gdm"

# Disable automatic hibernation
# https://wiki.archlinux.org/title/GDM#GDM_auto-suspend_.28GNOME_3.28.29
sudo -u gdm dbus-launch gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
