#!/bin/bash

BITWARDEN_FOLDER="$HOME/.bitwarden"
BITWARDEN_APPIMAGE_NAME="BitWarden.AppImage"

cd ~/downloads
curl -L 'https://vault.bitwarden.com/download/?app=desktop&platform=linux' --output $BITWARDEN_APPIMAGE_NAME

chmod +x $BITWARDEN_APPIMAGE_NAME

mkdir -p $BITWARDEN_FOLDER
mv -f $BITWARDEN_APPIMAGE_NAME $BITWARDEN_FOLDER

echo "[gem] [bitwarden] Installed to $BITWARDEN_FOLDER"