#!/bin/bash

BITWARDEN_FOLDER="$HOME/.bitwarden"

if [[ $1 = "r" ]]; then
    rm -rf $BITWARDEN_FOLDER

    exit 0
fi

cd ~/downloads
curl -L 'https://vault.bitwarden.com/download/?app=desktop&platform=linux' --output BitWarden.AppImage
mkdir -p $BITWARDEN_FOLDER
mv -f BitWarden.AppImage $BITWARDEN_FOLDER

echo "[gem] [bitwarden] Installed to $BITWARDEN_FOLDER"