#!/bin/bash

CONFIG_FOLDER="$HOME/.config"
CONFIG="$CONFIG_FOLDER/code-flags.conf"

DEPS="gnome-keyring libsecret libgnome-keyring"

gem pac S $DEPS
gem aur S visual-studio-code-bin

mkdir -p $CONFIG_FOLDER
echo "--ozone-platform-hint=auto" | tee $CONFIG