#!/bin/bash

CODE_DESKTOP="/usr/share/applications/code.desktop"

if [[ $1 = "r" ]]; then
    sudo rm -f $CODE_DESKTOP
    
    exit 0
fi

cd ~/downloads
wget -O vscode.tar.xf
tar -xf vscode.tar.xf
rm vscode.tar.xf

printf '[Desktop Entry]\nName=Code\nExec=/usr/bin/code --ozone-platform=wayland\nType=Application\n' | sudo tee $CODE_DESKTOP