#!/bin/bash

DEPS="git vim which tree ninja cmake make wget unzip fuse2 base-devel"

YAY_FOLDER="$HOME/downloads/yay"

if [[ $1 = "r" ]]; then
    gem pac R $DEPS
    gem pac R yay

    exit 0
fi

gem pac S $DEPS

git config --global credential.helper store

git clone https://aur.archlinux.org/yay.git $YAY_FOLDER
cd $YAY_FOLDER
makepkg -si
cd $HOME
rm -rf $YAY_FOLDER
yay