#!/bin/bash

DISCORD_FOLDER="$HOME/.discord"
DISCORD_TAR_NAME="Discord.tar.gz"
DISCORD_APPIMAGE_NAME="Discord.AppImage"

if [[ $1 = "r" ]]; then
    rm -rf $DISCORD_FOLDER

    exit 0
fi

cd ~/downloads
curl -L 'https://discord.com/api/download?platform=linux&format=tar.gz' --output $DISCORD_TAR_NAME

rm -rf $DISCORD_FOLDER
mkdir -p $DISCORD_FOLDER

tar -xf $DISCORD_TAR_NAME -C $DISCORD_FOLDER

echo "[gem] [discord] Installed to $DISCORD_FOLDER"