#!/bin/bash

if [[ $1 = "r" ]]; then
    sudo rm /usr/local/bin/earthly

    exit 0
fi

# https://earthly.dev/get-earthly
sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'