#!/bin/bash

DEPS="base-devel gdb ninja gcc cmake meson libxcb xcb-proto xcb-util xcb-util-keysyms \
libxfixes libx11 libxcomposite xorg-xinput libxrender pixman wayland-protocols \
cairo pango seatd libxkbcommon xcb-util-wm xorg-xwayland libinput xcb-util-cursor wlroots"

HYPR_DIR="$HOME/hypr"
HYPR_PAPER_DIR="$HYPR_DIR/hyprpaper"
HYPR_WAYBAR_DIR="$HYPR_DIR/waybar"
HYPR_VERSION="a22e117"
# b0d86a7 no cursor
# a22e117 no cursor

HYPR_XDG_DIR="$HYPR_DIR/xdg"

HYPR_PICKER_DIR="$HYPR_DIR/picker"

ROFI_DIR="$HYPR_DIR/rofi"

WAYLAND_SESSIONS_DIR="/usr/share/wayland-sessions"
X_SESSIONS_DIR="/usr/share/xsessions"

remove_hypr_dir() {
    rm -rf $HYPR_DIR
}

if [[ $1 = "r" ]]; then
    gem pac R $DEPS
    gem pac R foot
    # gem pac R otf-font-awesome gtk-mm
    gem pac R nnn
    gem pac R rofi
    gem pac R ydotool
    gem aur R swaylock-effects
    remove_hypr_dir

    exit 0
fi

gem pac S $DEPS

sudo rm -rf $HYPR_DIR
git clone https://github.com/hyprwm/Hyprland $HYPR_DIR || exit 1
cd $HYPR_DIR
git checkout "$HYPR_VERSION" || exit 1
git submodule update --init --recursive || exit 1
# sed -i 's/glFlush();/glFinish();/g' ./subprojects/wlroots/render/gles2/renderer.c
sudo make install || exit 1
# paru -S hyprland-nvidia-git

sudo mkdir -p $WAYLAND_SESSIONS_DIR
sudo cp /opt/gem/ext/hyprland.desktop $WAYLAND_SESSIONS_DIR
sudo mkdir -p $X_SESSIONS_DIR
sudo cp /opt/gem/ext/hyprland.desktop $X_SESSIONS_DIR

echo "[gem] [hyprland] [hyprpaper]"
git clone https://github.com/hyprwm/hyprpaper.git $HYPR_PAPER_DIR
cd $HYPR_PAPER_DIR
make all
sudo cp ./build/hyprpaper /usr/local/bin

#echo "[gem] [hyprland] [waybar]"
#gem pac S otf-font-awesome gtk-mm
#git clone https://github.com/Alexays/Waybar $HYPR_WAYBAR_DIR
#cd $HYPR_WAYBAR_DIR
#meson build
#sudo ninja -C build install

echo "[gem] [hyprland] [nnn]"
gem pac S nnn

echo "[gem] [hyprland] [mako]"
gem pac S mako

echo "[gem] [hyprland] [foot]"
gem pac S foot

echo "[gem] [hyprland] [ydotool]"
gem pac S ydotool
sudo chmod u+s /bin/ydotool /bin/ydotoold # Allow non-root users to use it

#echo "[gem] [hyprland] [xdg-desktop-portal-hyprland]"
#git clone https://github.com/hyprwm/xdg-desktop-portal-hyprland.git $HYPR_XDG_DIR
#cd $HYPR_XDG_DIR
#meson build --prefix=/usr
#sudo ninja -C build install
## sudo cp build/xdg-desktop-portal-hyprland /usr/bin

# Does not work with NVIDIA: https://github.com/hyprwm/hyprpicker/issues/28
#echo "[gem] [hyprland] [hyprpicker]"
#git clone https://github.com/hyprwm/hyprpicker.git $HYPR_PICKER_DIR
#cd $HYPR_PICKER_DIR
#make all
#sudo cp ./build/hyprpicker /usr/local/bin

#echo "[gem] [hyprland] [rofi]"
#git clone https://github.com/lbonn/rofi $ROFI_DIR
#cd $ROFI_DIR
#meson setup build
#sudo ninja -C build install

#echo "[gem] [hyprland] [rofi] [rofimoji]"
#gem pac S rofimoji

gem aur S swaylock-effects

echo "[gem] [hyprland] [pavucontrol]"
gem pac S pavucontrol
