#!/bin/bash

REMAPPER_CONFIG_EXT_FOLDER="/opt/gem/ext/input-remapper"
REMAPPER_CONFIG_FOLDER="$HOME/.config"

if [[ $1 = "r" ]]; then
    gem pac R polkit-gnome
    yay -R input-remapper-git

    exit 0
fi

gem pac S polkit-gnome
yay -S input-remapper-git

sudo systemctl enable input-remapper

mkdir -p $REMAPPER_CONFIG_FOLDER
cp -rf $REMAPPER_CONFIG_EXT_FOLDER $REMAPPER_CONFIG_FOLDER
