#!/bin/bash

DEPS="keyd"

REMAPPER_CONFIG_EXT_FOLDER="/opt/gem/ext/keyd.conf"
REMAPPER_CONFIG_PATH="/etc/keyd/default.conf"

gem aur S $DEPS

sudo systemctl enable keyd

sudo cp -f "$REMAPPER_CONFIG_EXT_FOLDER" "$REMAPPER_CONFIG_PATH"

sudo systemctl restart keyd
