#!/bin/bash

SPOTIFY_QT_FOLDER="$HOME/spotify-qt"

rm -rf $SPOTIFY_QT_FOLDER

if [[ $1 = "r" ]]; then
    # ^
    sudo rm -f /usr/local/bin/spotify-qt

    exit 0
fi

git clone --branch stable https://github.com/kraxarn/spotify-qt.git $SPOTIFY_QT_FOLDER
cd $SPOTIFY_QT_FOLDER
mkdir build
cd build
cmake .. -G Ninja
cmake --build .
sudo cp ./spotify-qt /usr/local/bin/spotify-qt