#!/bin/bash

echo "[gem] [enable] [multilib] in /etc/pacman.conf"
sudo sed -i "/multilib\]/s/^#//g" /etc/pacman.conf
sudo sed -i '/multilib\]/{N;s/\n#/\n/}' /etc/pacman.conf
sudo pacman -Sy

gem pac S steam