#!/bin/bash

VMWARE_FOLDER="$HOME/.vmware"

if [[ $1 = "r" ]]; then
    gem aur R vmware-workstation

    exit 0
fi

gem aur S vmware-workstation
sudo modprobe -a vmw_vmci vmmon

mkdir -p $VMWARE_FOLDER
printf "#!/bin/bash\n\nsudo systemctl start vmware-networks\nsudo systemctl start vmware-usbarbitrator\nvmware\nsudo systemctl stop vmware-networks\nsudo systemctl stop vmware-usbarbitrator\n" | tee $VMWARE_FOLDER/vmware.sh
