#!/bin/bash

DEPS="intel-oneapi-basekit"

if [[ $1 = "r" ]]; then
    gem pac R $DEPS

    exit 0
fi

gem pac S $DEPS

# wget https://registrationcenter-download.intel.com/akdlm/irc_nas/19079/l_BaseKit_p_2023.0.0.25537.sh
# sudo sh ./l_BaseKit_p_2023.0.0.25537.sh