#!/bin/bash

# DEPS="intel-oneapi-basekit"

WORKING_FOLDER="$HOME/downloads/vtune"

if [[ $1 = "r" ]]; then
    exit 0
fi

rm -rf $WORKING_FOLDER
mkdir -p $WORKING_FOLDER
cd $WORKING_FOLDER

wget https://registrationcenter-download.intel.com/akdlm/irc_nas/19079/l_BaseKit_p_2023.0.0.25537.sh
sudo sh ./l_BaseKit_p_2023.0.0.25537.sh