#!/bin/bash

if [[ $1 = "r" ]]; then
    gem pac R zsh exa

    exit 0
fi

gem pac S zsh exa

yay -S zsh-theme-powerlevel10k-git
echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' | tee ~/.zshrc

git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.zsh/zsh-autosuggestions
echo 'source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh' | tee -a ~/.zshrc

# chsh -l
sudo chsh -s /bin/zsh

# https://drasite.com/blog/Pimp%20my%20terminal
echo "bindkey '^[[2~' overwrite-mode" | tee -a ~/.zshrc
echo "bindkey '^[[3~' delete-char" | tee -a ~/.zshrc
echo "bindkey '^[[H' beginning-of-line" | tee -a ~/.zshrc
echo "bindkey '^[[1~' beginning-of-line" | tee -a ~/.zshrc
echo "bindkey '^[[F' end-of-line" | tee -a ~/.zshrc
echo "bindkey '^[[4~' end-of-line" | tee -a ~/.zshrc
echo "bindkey '^[[1;5C' forward-word" | tee -a ~/.zshrc
echo "bindkey '^[[1;5D' backward-word" | tee -a ~/.zshrc
echo "bindkey '^[[3;5~' kill-word" | tee -a ~/.zshrc
echo "bindkey '^[[5~' beginning-of-buffer-or-history" | tee -a ~/.zshrc
echo "bindkey '^[[6~' end-of-buffer-or-history" | tee -a ~/.zshrc
echo "unsetopt NO_BEEP" | tee -a ~/.zshrc
echo "unsetopt NO_MATCH" | tee -a ~/.zshrc
echo "setopt AUTO_CD" | tee -a ~/.zshrc # Type '..' instead of 'cd ..''
echo "setopt NOMATCH" | tee -a ~/.zshrc
echo "setopt NOTIFY" | tee -a ~/.zshrc
echo "setopt INTERACTIVE_COMMENTS" | tee -a ~/.zshrc # Comments in shel
echo "setopt MAGIC_EQUAL_SUBST" | tee -a ~/.zshrc # Helps with expansion edge case
echo "setopt NULL_GLOB" | tee -a ~/.zshrc # Less reporting

echo "alias ls=exa" | tee -a ~/.zshrc # ls is exa

# Background Color
echo "sed -i \"/-g POWERLEVEL9K_BACKGROUND=/c\  typeset -g POWERLEVEL9K_BACKGROUND=16\" $HOME/.p10k.zsh" | tee -a ~/.zshrc

echo "[gem] Reboot for zsh configuration to take effect..."

zsh